theme: jekyll-theme-minimal
author: Yo mismo
email: Correo@domain.com
description: 
  Some details about myself. Dedicated. Determined. Defecated.

# social links
twitter_username: RealOviedo
github_username:  gronert-m
